---
- name: Зміна паролю юзера cssuport на SV
  hosts: all
  gather_facts: no
  collections:
    - community.windows
  vars:
    collections_paths: /var/lib/awx/projects/collections
  tasks:
  - name: shell
    shell: whoami
  - debug:
      msg: msg
  - name: shell
    shell: whoami
  - name: Get the LAPS password using Kerberos auth, relies on kinit already being called
    set_fact:
      ansible_password: "{{ lookup('windows.laps_password', 'SERVER', domain='dc01.ansible.com') }}"
