---
- name: laps
  hosts: all
  gather_facts: no
  vars:
    ansible_pipelining: true

  tasks:
  - name: shell
    shell: whoami
  - debug:
      msg: msg
  - name: shell
    shell: whoami
    
  - name: Use Simple auth over LDAPS
    set_fact:
      ansible_password: "{{ lookup('laps_password', 'server',
                                 domain='dc01.ansible.com',
                                 auth='simple',
                                 scheme='ldaps',
                                 username='username@ANSIBLE.COM',
                                 password=pass) }}"

#  - name: Get the LAPS password using Kerberos auth, relies on kinit already being called
#    set_fact:
#      ansible_password: "{{ lookup('community.windows.laps_password', 'SERVER', domain='dc01.ansible.com') }}"
