---
- name: laps
  hosts: all
  gather_facts: no
  connection: paramiko
#  collections:
#    - community.windows
#  vars:
#    ansible_pipelining: true
#    ansible_ssh_pipelining: 1
#    collections_paths: /var/lib/awx/projects/collection
  tasks:
  - name: shell
    shell: whoami
  - debug:
      msg: msg
  - name: shell
    shell: whoami
    
  - name: Use Simple auth over LDAPS
    set_fact:
      ansible_password: "{{ lookup('laps_password', 'server',
                                 domain='dc01.ansible.com',
                                 auth='simple',
                                 scheme='ldaps',
                                 username='username@ANSIBLE.COM',
                                 password='SuperSecret123') }}"

#  - name: Get the LAPS password using Kerberos auth, relies on kinit already being called
#    set_fact:
#      ansible_password: "{{ lookup('community.windows.laps_password', 'SERVER', domain='dc01.ansible.com') }}"
