---
- name: laps
  hosts: all
  gather_facts: no 
  collections:
    - name: community.windows
      source: https://github.com/ansible-collections/
      type: git
  tasks:
  - name: shell
    shell: whoami
  - debug:
      msg: msg
  - name: shell
    shell: whoami
  - name: Get the LAPS password using Kerberos auth, relies on kinit already being called
    set_fact:
      ansible_password: "{{ lookup('community.windows.laps_password', 'SERVER', domain='dc01.ansible.com') }}"
